### ISSUE TITLE
Generate relations in database

### ISSUE THREAD

**Issue by ankitjena** [graphql-heroes/graphql-backend-gen#11]
**Scope**
Currently relations between database tables are not being created. We can implement this by checking for isType flag which is true for relations in types. Though problem arises as we don't have full scope of data and how relationships are mapped(type of relation - onetomany, manytomany for example).

**Suggested implementation**
A good approach would be to use custom directives to ask user the type of relationship. Then we can
* Create relationship using foreign key if directive is not provided.
* if directive is provided, most probably in case of manytomany relation, we can create a separate table and create manytomany relation between tables.

Refers to part one of #7

**Comment by ankitjena** [comment]
```
type Post {
  id: ID! @unique
  title: String!
  content: String!
  author: User
  comments: [Comment!]!
}

type User {
  id: ID! @unique
  username: String! @unique
  posts: [Post!]!
  comments: [Comment!]!
}

type Comment {
  id: ID! @unique
  text: String!
  post: Post!
  writtenBy: User!
}
```
In case of something like this, there are mostly one to many relations, and one to one. So how should we proceed, as creating one to one relations from Comment to Post seems as the same thing as one to many relation from Post to Comment(unclear about implementation of one to many).

**Comment by wtrocki** [comment]
Yeah. I would say that OneToMany will be used in most of the cases.
OneToMany simply puts field on the relationship type. 
For example
> comments: [Comment!]!

Can put some field on Comment table. 
However, we do not know field name that is where directive comes

`comments: [Comment!]! @OneToMany(field="user_comments")`

**Comment by ankitjena** [comment]
Just to be clear 
```
table.integer(x)
table.foreign(x).references('id').inTable('something')
```
This is produces a onetoone relation between x and id of table 'something'?

**Comment by wtrocki** [comment]
http://lmgtfy.com/?q=onetomany+relationship+explained

**Comment by ankitjena** [comment]
> Can put some field on Comment table.
> However, we do not know field name that is where directive comes.
> For example
> 
> `comments: [Comment!]! @OneToMany(field="user_comments")`
> 
> Gives us all info required to generate resolvers and tables.

That makes sense. So we can create three directives and form relations accordingly.
```
directive @OneToOne on FIELD
directive @OneToMany(field: String!) on FIELD
directive @ManyToMany(tablename: String!) on FIELD
```
Suggestions?

**Comment by wtrocki** [comment]
This makes sense
