### ISSUE TITLE
Project name ideas

### ISSUE THREAD

**Issue by wtrocki** [graphql-heroes/graphql-backend-gen#22]
Long project names are hard and it is best to rename project on early phase to avoid npm package problems etc.

Any suggestions for name:

Ideas? @graphql-heroes/rh-graphql-team @ankitjena

**Comment by wtrocki** [comment]
# Suggestions from my POV

👨‍🏭 bakendix
🇩🇪 girge

**Comment by wtrocki** [comment]
`Generix ` - clever :)

**Comment by ankitjena** [comment]
Generix sounds cool to me :100:

**Comment by wtrocki** [comment]
But then there is word generics that may be confusing

**Comment by wtrocki** [comment]
Another droppings:

- bagen 
- bacreato
- onbackend

**Comment by ankitjena** [comment]
* backneto
* badgen
* graphback
* gqlbackgen

**Comment by wtrocki** [comment]
Wow. Couple really solid ones. Going to check them for copyrights now and go back with the list.

**Comment by darahayes** [comment]
* graphtech
* graphswell
* graphtell
* graphtip
* graph-hint
* graphpraise
* graphspin
* graphsay
* graphpaint
* graphsketch
* graphweave

All available on npm.

**Comment by darahayes** [comment]
Oh and of course. graphfix as per @StephenCoady's recommendation 😄
