### ISSUE TITLE
Add support for relationships generation

### ISSUE THREAD

**Issue by wtrocki** [graphql-heroes/graphql-backend-gen#7]
Investigation for relationships generation. 

This can be split into separate issues:

- Creating relationships. (see https://github.com/graphql-heroes/graphql-resolver-gen/blob/28d62de39bf4b77040a203dbba5c701ff170ec57/src/datasource/DataResourcesManager.ts#L72-L74)

- Supporting Queries and Mutations for relationships

- Performance for relationships (DataLoader)

**Comment by wtrocki** [comment]
ping @ankitjena

**Comment by ankitjena** [comment]
Issue 1
Relationships in the database can be created using methods provided by Knex.

Problem arises as we don't have full scope of data and how the relationships are mapped, onetomany or manytomany.

Suggested approach would be to use custom directives to ask user the type of relationship. Then we can :
* Create default relationship using foreign key if any directive is not provided.
* If directive is provided, most probably in case of manytomany we can create a separate table and use foreign keys to create manytomany relation.

**Comment by wtrocki** [comment]
@ankitjena Feel free to create the separate issue and link this one as story.
